const data = {
  products: [
    {
      name: 'Potato',
      slug: 'potato',
      category: 'Vegetables',
      image: '/images/p1.jpg', // 679px × 829px
      price: 25,
      countInStock: 10,
      brand: 'Organic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh organic potato',
    },
    {
      name: 'Cauliflower',
      slug: 'cauliflower',
      category: 'Vegetables',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 20,
      brand: 'Inorganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh cauliflower',
    },
    {
      name: 'Radish',
      slug: 'radish',
      category: 'Vegetables',
      image: '/images/p3.jpg',
      price: 20,
      countInStock: 15,
      brand: 'Inorganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh radish',
    },
    {
      name: 'Turnip',
      slug: 'turnip',
      category: 'Vegetables',
      image: '/images/p4.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Organic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh organic turnip',
    },
    {
      name: 'Tomato',
      slug: 'tomato',
      category: 'Vegetables',
      image: '/images/p5.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Organic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh organic tomato',
    },
    {
      name: 'Garlic',
      slug: 'garlic',
      category: 'Vegetables',
      image: '/images/p6.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Inrganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh garlic',
    },
    {
      name: 'Onion',
      slug: 'onion',
      category: 'Vegetables',
      image: '/images/p7.jpg',
      price: 40,
      countInStock: 10,
      brand: 'Inorganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh onion',
    },
    {
      name: 'Cabbage',
      slug: 'cabbage',
      category: 'Vegetables',
      image: '/images/p8.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Organic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh organic cabbage',
    },
    {
      name: 'Chili',
      slug: 'chili',
      category: 'Vegetables',
      image: '/images/p9.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Inorganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh chili',
    },
    {
      name: 'Brinjal',
      slug: 'brinjal',
      category: 'Vegetables',
      image: '/images/p10.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Inorganic',
      rating: 0.0,
      numReviews: 0,
      description: 'farm fresh brinjal',
    },
  ],
};
export default data;
